# Generated by Django 4.2.2 on 2023-07-02 08:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='service')),
                ('title', models.CharField(max_length=80)),
                ('description', models.TextField()),
            ],
        ),
    ]
