# Generated by Django 4.2.2 on 2023-06-27 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('city', models.CharField(max_length=50)),
                ('phone', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('telegram', models.CharField(max_length=100)),
                ('instagram', models.CharField(max_length=100)),
                ('linkedin', models.CharField(max_length=100)),
                ('github', models.CharField(max_length=100)),
            ],
        ),
    ]
