# Generated by Django 4.2.2 on 2023-06-28 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='Condition',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='info',
            name='age',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='info',
            name='job',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='info',
            name='prof',
            field=models.ImageField(blank=True, upload_to='project'),
        ),
        migrations.AlterField(
            model_name='info',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='info',
            name='city',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='info',
            name='phone',
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
