# Generated by Django 4.2.2 on 2023-06-28 05:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0002_info_condition_info_age_info_job_info_name_info_prof_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='info',
            name='bio',
            field=models.TextField(blank=True),
        ),
    ]
