# Generated by Django 4.2.2 on 2023-06-28 09:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0004_message'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='gmail',
            new_name='email',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='message',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='fullname',
            new_name='name',
        ),
    ]
