# Generated by Django 4.2.2 on 2023-06-30 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0005_rename_gmail_message_email_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='message',
            new_name='body',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='name',
            new_name='fname',
        ),
    ]
