# Generated by Django 4.2.2 on 2023-06-30 11:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0006_rename_message_message_body_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='fname',
            new_name='name',
        ),
    ]
