# Generated by Django 4.2.2 on 2023-06-30 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0007_rename_fname_message_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='massage',
        ),
    ]
