# Generated by Django 4.2.2 on 2023-06-30 12:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0008_rename_body_message_massage'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='massage',
            new_name='body',
        ),
    ]
