# Generated by Django 4.2.2 on 2023-07-01 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0009_rename_massage_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='text',
        ),
    ]
