# Generated by Django 4.2.2 on 2023-07-01 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0010_rename_body_message_text'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
