# Generated by Django 4.2.2 on 2023-07-01 15:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0015_rename_sub_message_subj'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='subj',
            new_name='body',
        ),
    ]
