# Generated by Django 4.2.2 on 2023-07-01 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contactus_app', '0016_rename_subj_message_body'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='body',
            new_name='massage',
        ),
    ]
